### ISSUE TITLE
Issues executing the code

### ISSUE THREAD

**Issue by hanserasmus** [DavidLeutgeb/bookstack-export#3]
First off, thank you VERY much for this piece of code! I am looking at exactly this use case at the moment, and I am actually looking to try and export to pdf. For now, I am executing your code "as-is", but, being very new to Python I am running into errors which I am not sure how to solve. When executing it from withing pycharm, I get 
```
, line 44, in <module>
    file.write(book_html.text.encode('utf8'))
TypeError: write() argument must be str, not bytes
```
Any ideas what I can do to solve this?

**Comment by hugo-laestander** [comment]
I'm getting the same error when running the code.

Edit: I found the problem. The newest commit is breaking the script https://github.com/DavidLeutgeb/bookstack-export/commit/ec7aada1ed80ee8e3bd7b93f6ecb2949282dd058

To make it work. Simply change the line:
`file.write(book_html.text.encode('utf8'))`
back to:
`file.write(book_html.text)`

**Comment by hanserasmus** [comment]
Thank you. Changed that line of code and now it seems to work. Next up going to try and export it as PDF.

EDIT: PDF does not work. Seems changing the endpoint to markdown and the file extension to .md exports the file correctly.
